### ISSUE TITLE
[content-theme-docs] Incompatible with nuxt@2.15

### ISSUE THREAD

**Issue by Armaldio** [nuxt/content#785]
### Version
@nuxt/content: -
@nuxt/content-theme-docs: 0.10.1
nuxt: 2.15

### Reproduction Link
https://codesandbox.io/s/autumn-cookies-5sk2y?file=/package.json

### Steps to reproduce
1. Open sandbox
2. Wait for install
3. Open console

### What is Expected?
Custom vue components to be loaded

### What is actually happening?
A bunch of errors
![image](https://user-images.githubusercontent.com/3089715/108505424-a81d3480-72b7-11eb-8c6b-53f5e803ff6b.png)

Note: it works on nuxt 2.14.2

**Comment by regenrek** [comment]
See https://github.com/nuxt/components/issues/153

**Comment by foxted** [comment]
Hey @regenrek , running into the same issue with nuxt-content-docs 0.10.1 and nuxt 2.15.1. I installed nuxt-content-docs with the `npx create-nuxt-content-docs` command and I can't find the `lib/` folder. Anything I need to do to access this folder?

**Comment by regenrek** [comment]
Meanwhile just don't use 2.15

```
{
  "devDependencies": {
    "@nuxt/content-theme-docs": "0.8.2",
    "nuxt": "2.14.12"
  }
}
```

Example [package.json](https://github.com/regenrek/nujek/blob/main/docs/package.json)

**Comment by Soviut** [comment]
@regenrek I tried taking an existing npx installation (which automatically uses Nuxt 2.15.2), I deleted my `node_modules` directory, deleted `package-lock.json` and did npm install using the following deps

```
  "devDependencies": {
    "@nuxt/content-theme-docs": "0.8.2",
    "nuxt": "2.14.12"
  }
```

But I wound up getting a client error on first build

```
ERROR in ./.nuxt/client.js
Module build failed (from ./node_modules/babel-loader/lib/index.js):
Error: /home/.../.nuxt/client.js: Cannot find module '@babel/preset-env/lib/utils'
```

**Comment by regenrek** [comment]
@Soviut Didn't try it yet but maybe this can help you: https://docus.dev/more/migration
